# Generated by Django 5.2.14 on 2026-06-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewRc',
            fields=[
                ('now', models.DateField(auto_created=True, auto_now_add=True)),
                ('reg_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('chassis_number', models.CharField(max_length=27)),
                ('engine_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('son_of', models.CharField(max_length=40)),
                ('street_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('district1', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_date', models.CharField(max_length=50)),
                ('reg_valid', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=2)),
                ('emission_norms', models.CharField(max_length=20)),
                ('issue_date', models.CharField(max_length=20)),
                ('month_year_of_Mfg', models.CharField(max_length=15)),
                ('number_cylinder', models.CharField(max_length=2)),
                ('number_of_Axle', models.CharField(blank=True, max_length=2, null=True)),
                ('vehicle_class', models.CharField(max_length=75)),
                ('maker_name', models.CharField(max_length=75)),
                ('model_name', models.CharField(max_length=75)),
                ('color', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('seating', models.CharField(max_length=50)),
                ('standing', models.CharField(blank=True, max_length=15, null=True)),
                ('sleeper', models.CharField(blank=True, max_length=15, null=True)),
                ('unladen', models.CharField(max_length=15)),
                ('laden', models.CharField(max_length=15)),
                ('gross_combination', models.CharField(blank=True, max_length=15, null=True)),
                ('cubic', models.CharField(max_length=15)),
                ('horse_power', models.CharField(max_length=15)),
                ('wheel_base', models.CharField(max_length=15)),
                ('financer', models.CharField(blank=True, max_length=50, null=True)),
                ('rto_name', models.CharField(blank=True, max_length=50, null=True)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='front_rc_legacy_new_images/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='back_rc_legacy_new_images/')),
            ],
            options={
                'ordering': ('-now',),
            },
        ),
        migrations.CreateModel(
            name='OldRc',
            fields=[
                ('now', models.DateField(auto_created=True, auto_now_add=True)),
                ('reg_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('chassis_number', models.CharField(max_length=35)),
                ('engine_number', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=40)),
                ('son_of', models.CharField(max_length=40)),
                ('street_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('district1', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_date', models.CharField(max_length=50)),
                ('reg_valid', models.CharField(max_length=50)),
                ('fuel', models.CharField(blank=True, max_length=50, null=True)),
                ('serial', models.CharField(max_length=2)),
                ('owner_type', models.CharField(max_length=12)),
                ('month_year_of_Mfg', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=200)),
                ('wheel_base', models.CharField(max_length=20)),
                ('cubic', models.CharField(max_length=20)),
                ('number_cylinder', models.CharField(max_length=20)),
                ('ledan_unledan', models.CharField(max_length=50)),
                ('maker_name', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('seating', models.CharField(max_length=6)),
                ('rto_name', models.CharField(blank=True, max_length=50, null=True)),
                ('financer', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_valid', models.CharField(blank=True, default='LIFE TIME', max_length=50, null=True)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='front_rc_legacy_old_images/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='back_rc_legacy_old_images/')),
            ],
            options={
                'ordering': ('-now',),
            },
        ),
    ]
