# Generated by Django 5.0.3 on 2024-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_alter_balance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='recharge_amt',
            field=models.IntegerField(default=0),
        ),
    ]
