# Generated by Django 5.2.14 on 2026-06-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0005_billingconfig_fetch_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingconfig',
            name='app',
            field=models.CharField(choices=[('new', 'New App'), ('old', 'Old App')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='usagetransaction',
            name='app',
            field=models.CharField(choices=[('new', 'New App'), ('old', 'Old App')], default='new', max_length=10),
        ),
    ]
