# Generated by Django 5.2.14 on 2026-06-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_billingconfig_app_usagetransaction_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingconfig',
            name='app',
        ),
        migrations.AddField(
            model_name='billingconfig',
            name='debit_amount_old',
            field=models.IntegerField(default=0),
        ),
    ]
