# Generated by Django 5.0.3 on 2024-05-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontRcNew',
            fields=[
                ('now', models.DateField(auto_created=True, auto_now_add=True)),
                ('reg_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('chassis_number', models.CharField(max_length=27)),
                ('engine_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('son_of', models.CharField(max_length=40)),
                ('street_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('district1', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_date', models.CharField(max_length=50)),
                ('reg_valid', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=6)),
                ('serial', models.CharField(max_length=2)),
                ('emission_norms', models.CharField(max_length=20)),
                ('issue_date', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='FrontRcNew/')),
            ],
            options={
                'ordering': ('-now',),
            },
        ),
    ]
