# Generated by Django 5.0.3 on 2024-05-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackRcNew',
            fields=[
                ('now', models.DateField(auto_created=True, auto_now_add=True)),
                ('reg_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('reg_date', models.CharField(default='01-01-2023', max_length=50)),
                ('month_year_of_Mfg', models.CharField(max_length=15)),
                ('number_cylinder', models.CharField(max_length=2)),
                ('number_of_Axle', models.CharField(blank=True, max_length=2, null=True)),
                ('vehicle_class', models.CharField(max_length=75)),
                ('maker_name', models.CharField(max_length=75)),
                ('model_name', models.CharField(max_length=75)),
                ('color', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('seating', models.CharField(max_length=50)),
                ('standing', models.CharField(blank=True, max_length=15, null=True)),
                ('sleeper', models.CharField(blank=True, max_length=15, null=True)),
                ('unladen', models.CharField(max_length=15)),
                ('laden', models.CharField(max_length=15)),
                ('gross_combination', models.CharField(blank=True, max_length=15, null=True)),
                ('cubic', models.CharField(max_length=15)),
                ('horse_power', models.CharField(max_length=15)),
                ('wheel_base', models.CharField(max_length=15)),
                ('financer', models.CharField(blank=True, max_length=25, null=True)),
                ('rto_name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='back_rc_new_images/')),
                ('chassis_number', models.CharField(default='chassisnumber', max_length=27)),
                ('engine_number', models.CharField(default='enginenumber', max_length=20)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ('-now',),
            },
        ),
        migrations.AlterModelOptions(
            name='frontrcnew',
            options={},
        ),
        migrations.AlterField(
            model_name='frontrcnew',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='front_rc_new_images/'),
        ),
    ]
