# Generated by Django 5.0.3 on 2024-05-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrc', '0004_delete_backrcnew_delete_frontrcnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldRc',
            fields=[
                ('now', models.DateField(auto_created=True, auto_now_add=True)),
                ('reg_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('chassis_number', models.CharField(max_length=35)),
                ('engine_number', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=40)),
                ('son_of', models.CharField(max_length=40)),
                ('street_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('district1', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_date', models.CharField(max_length=50)),
                ('reg_valid', models.CharField(max_length=50)),
                ('fuel', models.CharField(blank=True, max_length=12, null=True)),
                ('serial', models.CharField(max_length=2)),
                ('owner_type', models.CharField(max_length=12)),
                ('month_year', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=200)),
                ('wheelbase', models.CharField(max_length=20)),
                ('cubic', models.CharField(max_length=20)),
                ('cylinder', models.CharField(max_length=20)),
                ('ledan_unledan', models.CharField(max_length=50)),
                ('maker', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('body_type', models.CharField(max_length=50)),
                ('seating', models.CharField(max_length=6)),
                ('rto', models.CharField(blank=True, max_length=50, null=True)),
                ('finance', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_valid', models.CharField(blank=True, default='LIFE TIME', max_length=50, null=True)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='front_rc_old_images/')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='back_rc_old_images/')),
            ],
            options={
                'ordering': ('-now',),
            },
        ),
    ]
