# Generated by Django 5.0.3 on 2025-08-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrc', '0005_oldrc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rc',
            fields=[
                ('now', models.DateField(auto_created=True, auto_now_add=True)),
                ('reg_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
    ]
