# Generated by Django 5.0.3 on 2025-08-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartrc', '0006_rc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldrc',
            old_name='maker',
            new_name='maker_name',
        ),
        migrations.RenameField(
            model_name='oldrc',
            old_name='cylinder',
            new_name='month_year_of_Mfg',
        ),
        migrations.RenameField(
            model_name='oldrc',
            old_name='month_year',
            new_name='number_cylinder',
        ),
        migrations.RenameField(
            model_name='oldrc',
            old_name='wheelbase',
            new_name='wheel_base',
        ),
    ]
