# Generated by Django 5.0.3 on 2025-08-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartrc', '0007_rename_maker_oldrc_maker_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldrc',
            old_name='model',
            new_name='model_name',
        ),
    ]
