# Generated by Django 5.0.3 on 2025-08-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrc', '0008_rename_model_oldrc_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrc',
            name='fuel',
            field=models.CharField(max_length=12),
        ),
    ]
