# Generated by Django 5.0.3 on 2026-01-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartrc', '0009_alter_newrc_fuel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldrc',
            old_name='finance',
            new_name='financer',
        ),
        migrations.RenameField(
            model_name='oldrc',
            old_name='rto',
            new_name='rto_name',
        ),
    ]
