# Generated by Django 5.2.14 on 2026-06-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrc', '0010_rename_finance_oldrc_financer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrc',
            name='financer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='newrc',
            name='fuel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='oldrc',
            name='fuel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
