# Generated by Django 5.2.14 on 2026-06-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartrc', '0011_alter_newrc_financer_alter_newrc_fuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrc',
            name='template',
            field=models.CharField(blank=True, default='NT_TN', max_length=50),
        ),
        migrations.AddField(
            model_name='oldrc',
            name='template',
            field=models.CharField(blank=True, default='NT_TN', max_length=50),
        ),
    ]
