# Generated by Django 5.2.14 on 2026-06-21 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartrc', '0012_newrc_template_oldrc_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldrc',
            name='template',
        ),
    ]
