# Generated by Django 5.0.3 on 2025-11-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostDetail',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_active'],
            },
        ),
    ]
