# Generated by Django 5.2.14 on 2026-06-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_call', models.BooleanField(default=False)),
            ],
        ),
    ]
